name: Node.js CI Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install depedencies
        run: npm install
        
      - name: Build check
        run: npm build
      
      - name: Test check
        run: npm test
        
      - name: Lint check
        run: npm lint
