name: Node.js CI Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the source code...
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install
        
      - name: TORI Build check
        run: npm run build
      
      - name: TORI Test check
        run: npm run test
        
      - name: TORI Lint check
        run: npm run lint
